### ISSUE TITLE
[Feature request] Allow only one instances of TIC-80 to run at once

### ISSUE THREAD

**Issue by fmaida** [Gi972/tic80-vscode#3]
Thank you very much for your plugin,

Each time I press CMD+r / CTRL+R on my computer, a new instance of TIC-80 is opened; would it be possible to limit the maximum number of instances to just one and have that instance reload the lua file and relaunch the .tic cartridge instead?

**Comment by Gi972** [comment]
Hello,

I work on a new version of plugin for this, I hope to release soon. ;-)

**Comment by fmaida** [comment]
Thank you very much
