### ISSUE TITLE
Question: API markdown

### ISSUE THREAD

**Issue by BuoYancYdabl** [Gi972/tic80-vscode#6]
So Im not really familiar with VSC, but what I know for sure that this piece of software is not updating anymore, and TIC-80 already released 1.x version, what means that a lot of API's has been added. Is there any way I can make markdowns for API myself? Like set the color for it, description and type?

**Comment by Gi972** [comment]
Hello @BuoYancYdabl ,

there is a long time, I don't touch TIC-80.
what do you mean by make a markdows for api ? 
a syntax highlight guide for vs editor?

I guess it's possible.

**Comment by BuoYancYdabl** [comment]
Thank you! Any useful links?

**Comment by Gi972** [comment]
@BuoYancYdabl 

look at this: [vscode syntax-highlight-guide](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#:~:text=Syntax%20highlighting%20determines%20the%20color,and%20comments%20and%20variable%20names.)

you can take also example with [the pico8 Highlight extension for vscode](https://github.com/grumpydev/pico8vscodeeditor/blob/master/syntaxes/lua.tmLanguage.json)

enjoy ;-)
